[project]
name = "thrivewell"
version = "0.1.0"
description = ""
authors = ["MightContainNuts <mightcontainnuts@icloud.com>"]
dependencies = [
    "flask>=3.1.0",
    "pytest>=8.3.4",
    "pre-commit>=4.1.0",
    "pytest-sugar>=1.0.0",
    "pytest-cov>=6.0.0",
    "gunicorn>=23.0.0",
    "flask-sqlalchemy>=3.1.1",
    "python-dotenv>=1.0.1",
    "psycopg2>=2.9.10",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.38",
    "flask-migrate>=4.1.0"
]
requires-python = ">=3.13"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
