[tool.poetry]
name = "thrivewell"
version = "0.1.0"
description = "Companion app using AI"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
poetry-core = "^2.1.1"
flask = "^3.1.0"
flask-migrate = "^4.1.0"
dotenv = "^0.9.9"
gunicorn = "^23.0.0"
flask-sqlalchemy = "^3.1.1"
psycopg2 = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
