"""create chat history

Revision ID: 45d418790c72
Revises: 61139f5968d4
Create Date: 2025-03-07 16:25:38.314443

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "45d418790c72"
down_revision = "61139f5968d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_history",
        sa.Column("history_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column(
            "message_type",
            sa.Enum("SYSTEM", "USER", name="messagetypes"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.profile_id"],
        ),
        sa.PrimaryKeyConstraint("history_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_history")
    # ### end Alembic commands ###
