"""create chat history

Revision ID: 533907df8b0f
Revises: 45d418790c72
Create Date: 2025-03-07 16:37:39.693956

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "533907df8b0f"
down_revision = "45d418790c72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("keywords", postgresql.ARRAY(sa.String()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_column("keywords")

    # ### end Alembic commands ###
