"""changed column to vectors  for embeddings

Revision ID: 57e98a80c677
Revises: 5521b9da2e17
Create Date: 2025-03-02 18:43:11.186615

"""
import pgvector.sqlalchemy.vector
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "57e98a80c677"
down_revision = "5521b9da2e17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vector_embeddings", schema=None) as batch_op:
        batch_op.alter_column(
            "embedding",
            existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
            type_=pgvector.sqlalchemy.vector.VECTOR(dim=300),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vector_embeddings", schema=None) as batch_op:
        batch_op.alter_column(
            "embedding",
            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=300),
            type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
