"""removed mood, added json colum for asi response

Revision ID: 61139f5968d4
Revises: edb5ed1d5101
Create Date: 2025-03-04 20:07:03.237841

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61139f5968d4"
down_revision = "edb5ed1d5101"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mood_history")
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.alter_column(
            "ai_response",
            existing_type=sa.TEXT(),
            type_=sa.JSON(),
            existing_nullable=True,
        )

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_column("mood")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mood",
                postgresql.ENUM(
                    "VERY_POSITIVE",
                    "SOMEWHAT_POSITIVE",
                    "NEUTRAL",
                    "SOMEWHAT_NEGATIVE",
                    "VERY_NEGATIVE",
                    name="moodstatus",
                ),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.alter_column(
            "ai_response",
            existing_type=sa.JSON(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.create_table(
        "mood_history",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "mood",
            postgresql.ENUM(
                "VERY_POSITIVE",
                "SOMEWHAT_POSITIVE",
                "NEUTRAL",
                "SOMEWHAT_NEGATIVE",
                "VERY_NEGATIVE",
                name="moodstatus",
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="mood_history_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="mood_history_pkey"),
    )
    # ### end Alembic commands ###
