"""add medication table with side effects

Revision ID: 7281b36940b2
Revises: 640c705f2995
Create Date: 2025-03-03 16:34:45.587249

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "7281b36940b2"
down_revision = "640c705f2995"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("fda_code", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "side_effects", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True
        ),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fda_code"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cancer_type", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("medication", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_column("medication")
        batch_op.drop_column("cancer_type")

    op.drop_table("medications")
    # ### end Alembic commands ###
