"""create chat history

Revision ID: 7a74e771c992
Revises: 533907df8b0f
Create Date: 2025-03-07 16:46:20.953873

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "7a74e771c992"
down_revision = "533907df8b0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("mood", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.drop_column("mood")

    # ### end Alembic commands ###
