"""initial migration

Revision ID: 7b8bc7b56b24
Revises: 
Create Date: 2025-03-13 11:49:46.733374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b8bc7b56b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_embeddings')
    op.drop_table('medications')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('medication')
        batch_op.drop_column('cancer_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancer_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('medication', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.create_table('medications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fda_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('side_effects', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='medications_pkey'),
    sa.UniqueConstraint('fda_code', name='medications_fda_code_key'),
    sa.UniqueConstraint('name', name='medications_name_key')
    )
    op.create_table('vector_embeddings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], name='vector_embeddings_profile_id_fkey'),
    sa.UniqueConstraint('url', name='vector_embeddings_url_key')
    )
    # ### end Alembic commands ###
