"""add journal entry column in Journal db - duh

Revision ID: 9e8b754f08ef
Revises: 7281b36940b2
Create Date: 2025-03-04 16:14:18.458694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e8b754f08ef"
down_revision = "7281b36940b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entry", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.drop_column("entry")

    # ### end Alembic commands ###
