"""create chat history

Revision ID: a5468d256c59
Revises: 89504e98adde
Create Date: 2025-03-07 17:09:00.216165

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "a5468d256c59"
down_revision = "89504e98adde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("conversation_id", sa.UUID(), nullable=False)
        )
        batch_op.drop_column("history_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "history_id", sa.UUID(), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("conversation_id")

    # ### end Alembic commands ###
