"""create chat history

Revision ID: d1b980b6f289
Revises: 7a74e771c992
Create Date: 2025-03-07 16:50:38.516485

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d1b980b6f289"
down_revision = "7a74e771c992"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("query", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("response", sa.Text(), nullable=True))
        batch_op.drop_column("message_type")
        batch_op.drop_column("message")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_history", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "message_type",
                postgresql.ENUM("SYSTEM", "USER", name="messagetypes"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("response")
        batch_op.drop_column("query")

    # ### end Alembic commands ###
