"""add response entry column in Journal db - duh

Revision ID: dbebfd415efb
Revises: 9e8b754f08ef
Create Date: 2025-03-04 16:38:10.125677

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "dbebfd415efb"
down_revision = "9e8b754f08ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("response", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.drop_column("response")

    # ### end Alembic commands ###
