"""add response entry column in Journal db - duh

Revision ID: edb5ed1d5101
Revises: dbebfd415efb
Create Date: 2025-03-04 19:25:00.916235

"""
from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "edb5ed1d5101"
down_revision = "dbebfd415efb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_response", sa.Text(), nullable=True))
        batch_op.drop_column("sentiment")
        batch_op.drop_column("response")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("response", sa.TEXT(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "sentiment",
                postgresql.ENUM(
                    "VERY_POSITIVE",
                    "SOMEWHAT_POSITIVE",
                    "NEUTRAL",
                    "SOMEWHAT_NEGATIVE",
                    "VERY_NEGATIVE",
                    name="moodstatus",
                ),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("ai_response")

    # ### end Alembic commands ###
