"""Fix embeddings vector size to 384

Revision ID: f4fd6383755a
Revises: 5240098bce48
Create Date: 2025-03-02 20:15:53.693160

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = "f4fd6383755a"
down_revision = "5240098bce48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vector_embeddings", schema=None) as batch_op:
        batch_op.alter_column(
            "embedding",
            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=300),
            type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vector_embeddings", schema=None) as batch_op:
        batch_op.alter_column(
            "embedding",
            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
            type_=pgvector.sqlalchemy.vector.VECTOR(dim=300),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
