name: Create Branch for In Progress Issue

on:
  project_card:
    types:
      - moved

jobs:
  create-branch:
    runs-on: ubuntu-latest
    if: |
      github.event.project_card.column_name == 'In Progress'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create new branch for issue
        run: |
          ISSUE_NUMBER=$(echo ${{ github.event.project_card.content_url }} | grep -o '[0-9]\+')
          BRANCH_NAME="issue-${ISSUE_NUMBER}-in-progress"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
